
#********* LOVELACE *********#
  - url: /community_plugin/fan-control-entity-row/fan-control-entity-row.js
    type: js



  - title: Ventilation
    icon: mdi:fan
    panel: true #true = fuld bredde
    cards:
      - id: dd0f73bf83a14ef5be97d0389a5be361  # Automatically created id
        type: horizontal-stack
        cards:
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: thermostat
    #                title: Nilan ventilationssystem
                    entity: climate.nilan_ventilation
                  - type: vertical-stack
                    cards:
                      - type: gauge
                        name: Indsugning
                        unit: '%'
                        entity: sensor.nilan_indblaes_procent
                        severity:
                          green: 0
                          yellow: 68
                          red: 70
                      - type: gauge
                        name: Udblæsning
                        unit: '%'
                        entity: sensor.nilan_udblaes_procent
                        severity:
                          green: 0
                          yellow: 68
                          red: 70
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: fan.nilan_speed
                    type: custom:fan-control-entity-row
                    name: Ventilationshastighed
                    customTheme: true
                  - entity: binary_sensor.nilan_controller
                  - entity: binary_sensor.nilan_modbus
                  - entity: binary_sensor.nilan_filterstatus
                    icon: mdi:air-filter

          - type: picture-elements
            image: /local/ventilation4.png
            elements:
              - type: state-label 
                entity: sensor.nilan_indsugningstemp
                style:
                  top: 9.0%
                  left: 30.5%
                  color: white
                  font-size: 150%
              - type: state-label 
                entity: sensor.nilan_afkast_temp
                style:
                  top: 9.0%
                  left: 71.5%
                  color: white
                  font-size: 150%
              - type: state-label 
                entity: sensor.nilan_rumtemp
                style:
                  top: 65.2%
                  left: 30.5%
                  color: white
                  font-size: 150%
              - type: state-label 
                entity: sensor.nilan_udblaesningstemp
                style:
                  top: 65.2%
                  left: 71.5%
                  color: white
                  font-size: 150%
              - type: state-label 
                entity: sensor.nilan_luftfugtighed
                style:
                  top: 77.2%
                  left: 51.0%
                  color: white
                  font-size: 150%

				  
				  
				  
				  
				  
				  
#********* SENSOR *********#

#################################
###  Nilan Temp Sensorer      ###
#################################    

- platform: mqtt
  name: "Nilan controllerboard temp"
  state_topic: "ventilation/temp/T0_Controller" #Controller board temperature
  unit_of_measurement: "°C"
  device_class: temperature
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan indsugningstemp"
  state_topic: "ventilation/temp/T1_Intake" #Fresh air intake temperature
  unit_of_measurement: "°C"
  device_class: temperature  
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan udblæsningstemp"
  state_topic: "ventilation/temp/T2_Inlet" #Inlet temperature (before heater)
  unit_of_measurement: "°C"
  device_class: temperature  
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan udblæsningstemp"
  state_topic: "ventilation/temp/T5_Cond" #Condenser temperature
  unit_of_measurement: "°C"
  device_class: temperature  
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan udblæsningstemp"
  state_topic: "ventilation/temp/T6_Evap" #Evaporator temperature
  unit_of_measurement: "°C"
  device_class: temperature  
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan indsugningstemp efter opvarmning"
  state_topic: "ventilation/temp/T7_Inlet" #Inlet temperature (after heater)
  unit_of_measurement: "°C"
  device_class: temperature
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan udendørstemp"
  state_topic: "ventilation/temp/T8_Outdoor" #Outdoor temperature
  unit_of_measurement: "°C"
  device_class: temperature
  value_template: >-
   {{ value | round(1) }}

- platform: mqtt
  name: "Nilan rumtemp"
  state_topic: "ventilation/temp/T10_Extern" #External room temperature
  unit_of_measurement: "°C"
  device_class: temperature  
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan brugerpanel-temp"
  state_topic: "ventilation/temp/T15_Room" #User panel room temperature
  unit_of_measurement: "°C"
  device_class: temperature  
  value_template: >-
   {{ value | round(1) }}
   
- platform: mqtt
  name: "Nilan afkast Temp" #temperaturen på luften der sendes tilbage udenfor
  state_topic: "ventilation/temp/T6_Evap"
  unit_of_measurement: "°C"
  device_class: temperature
  value_template: >-
   {{ value | round(1) }}

#################################
###  Nilan Fugt Sensor        ###
#################################        

- platform: mqtt
  name: "Nilan Luftfugtighed"
  state_topic: "ventilation/moist/RH"
  unit_of_measurement: "%"
  device_class: humidity
  value_template: >-
   {{ value | round(1) }}


#################################
###  Nilan Luftmængde Sensor  ###
#################################      

- platform: mqtt
  name: "Nilan Indblæs Procent"
  state_topic: "ventilation/speed/InletSpeed"
  value_template: >-
   {{ value | float | multiply(0.01) | round(0) }}
  unit_of_measurement: "%"

- platform: mqtt
  name: "Nilan Udblæs Procent"
  state_topic: "ventilation/speed/ExhaustSpeed"
  value_template: >-
   {{ value | float | multiply(0.01) | round(0) }}
  unit_of_measurement: "%" 
    
#################################
###Nilan Krydsveklser Effekt  ###
#################################      

- platform: mqtt
  name: "Nilan Krydsveklser Effektivitet"
  state_topic: "ventilation/inputairtemp/EffPct"
  value_template: >-
   {{ value | float | multiply(0.01) | round(0) }}
  unit_of_measurement: "%"     

  
  
  
  
  

#********* BINARY SENSOR *********#

#################################
### Nilan Bypass-Spjæld Sensor###
#################################       
  - platform: mqtt
    name: "Nilan Bypass"
    state_topic: "ventilation/output/BypassClose"
    payload_on: "0"
    payload_off: "1"
    device_class: opening
    
#################################
### Nilan Ping Sensor         ###
#################################  
  - platform: ping
    name: Nilan Controller
    host: 192.168.1.35
    count: 2
    scan_interval: 30  

#################################
### Nilan Filterstatus Sensor ###
#################################        

  - platform: mqtt
    name: "Nilan filterstatus"
    state_topic: "ventilation/info/AirFilter" #Airfilter alarm
    device_class: problem
    value_template: >-
            {% if value == "0" %}
            {{"Filter ok"}}
            {% else %}
            {{"Filter skal skiftes"}}
            {% endif %}
  
#################################
### Modbus error sensor       ###
#################################        

  - platform: mqtt
    name: "Nilan modbus"
    state_topic: "ventilation/error/modbus/" #Modbus alarm
    device_class: connectivity
    payload_on: "0"
    payload_off: "1"
